#!/usr/bin/env bash
set -eu

target=${DOTFILES_DIR:-~/.dotfiles}
if [ ! -e $target ]; then
    git clone https://github.com/rimmington/dothooks $target
fi

export DOTFILES_REPOS="${DOTFILES_REPOS:-https://github.com/rimmington/dotfiles}"

echo "DOTFILES_REPOS='${DOTFILES_REPOS}'" > $target/config
echo "DOTFILES_DIR='$target'" >> $target/config
echo "DOTFILES_UPDATE_EVERY=${DOTFILES_UPDATE_EVERY:-7200}" >> $target/config

$target/setup
