#!/usr/bin/env bash
set -eu

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $root/lib/default
source $root/config

cd $root
git submodule update --init --recursive

links_to_current_home() {
    [[ $(readlink $1) =~ ^$root/current/home/ ]]
}

not_even_a_link() {
    [ ! \( -L $1 -o -e $1 \) ]
}

setup_staging_home() {
    cleanDir $root/staging/home
    touch -a $root/staging/bash_suffix
    touch -a $root/staging/zsh_suffix
    find $root/staging/sources/*/hooks/post_update.d/ -type f | perl -e 'print sort{($p=$a)=~s!.*/!!;($q=$b)=~s!.*/!!;$p cmp$q}<>' | xargs -I {} bash -c "$root/runHookd {} || exit 255"
}

check_links() {
    pushd_ $root/staging/home
        find . -mindepth 1 | sed 's/^\.\///' > $root/staging/manifest
    popd_
    while read f; do
        if [ -d $root/staging/home/$f ]; then
            if ! (not_even_a_link ~/$f || [ -d ~/$f ]); then
                errol "~/$f exists and is not a directory"
                exit 1
            fi
        else
            if ! (not_even_a_link ~/$f || links_to_current_home ~/$f); then
                errol "~/$f exists and is not a symlink into $root"
                exit 1
            fi
        fi
    done < $root/staging/manifest
}

flip_current() {
    if [ -e $root/current ]; then
        rm -rf $root/old
        mv $root/current $root/old
    fi
    mv $root/staging $root/current
}

setup_links() {
    while read f; do
        if [ -d $root/current/home/$f ]; then
            mkdir -p
        else
            ln -sf $root/current/home/$f ~/$f
        fi
    done < $root/current/manifest
    if [ -e $root/old ]; then
        while read f; do
            if [ -d $root/old/$f ]; then
                if [ $(find ~/$f -maxdepth 0 -type d -empty 2>/dev/null) ]; then
                    rmdir ~/$f
                fi
            else
                if [ -L ~/$f ] && links_to_current_home ~/$f && [ ! -e ~/$f ]; then
                    info "Cleaning up ~/$f"
                    rm ~/$f
                fi
            fi
        done < $root/old/manifest
    fi
    # TODO: cleanup
}

remove_managed_from() {
    if [ -e "$1" ]; then
        sed_in_place '/#DOTFILES_MANAGED$/ d' "$1"
    fi
}

setup_shell_hooks() {
    remove_managed_from ~/.bashrc
    echo "$DOTFILES_DIR/update #DOTFILES_MANAGED" >> ~/.bashrc
    echo "source $DOTFILES_DIR/current/bash_suffix #DOTFILES_MANAGED" >> ~/.bashrc

    remove_managed_from ~/.zshrc
    echo "$DOTFILES_DIR/update #DOTFILES_MANAGED" >> ~/.zshrc
    echo "source $DOTFILES_DIR/current/zsh_suffix #DOTFILES_MANAGED" >> ~/.zshrc
}

setup_staging_home
check_links
flip_current
setup_links
setup_shell_hooks

info "Updated"
