#!/usr/bin/env bash

set -eu
root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

_set_vars() {
    OLD_HOME=$HOME
    HOME=$root/staging/home
    local d="$(pwd)"
    HERE_LIB=$root/current/${d#$root/staging/}
}

source $root/lib/for_hooks
info "Running $1"
pushd_ $(dirname $1)/../..
    _set_vars
    unset root
    source $1
popd_
