#!/usr/bin/env bash
set -e

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $root
#git submodule update --init --recursive
source ./lib

cleanDir $root/staging
do_clones() {
    mkdir -p $root/staging/sources
    local n=0
    for repo in $DOTFILES_REPOS; do
        n=$(( $n + 1 ))
        # http://stackoverflow.com/a/19482947
        local branch=${repo##*#}
        local remote=${repo%#*}
        local dest="$root/staging/sources/$n"

        if [[ "$branch" == "$repo" ]]; then
            branch=''
            info "Cloning $remote"
        else
            info "Cloning $remote branch $branch"
        fi

        git clone $remote $dest

        if [[ "$branch" != '' ]]; then
            pushd_ $dest
                git checkout -f $branch
                git reset --hard
            popd_
        fi
    done
}
do_clones

$root/post_update
